### ISSUE TITLE
Support IE9/10 media hack?

### ISSUE THREAD

**Issue by davatron5000** [jtangelder/grunt-stripmq#26]
Trying to use an IE9/10 specific `@media screen and (min-width:0\0)` hack (see "[Moving IE specific hacks into media blocks](http://keithclark.co.uk/articles/moving-ie-specific-css-into-media-blocks/)") but StripMQ (what we use for IE8 support) is exiting with an error:

```
{ [Error: Stripping media queries failed.] origError: [TypeError: Cannot read property '1' of null] }
```

Would it be possible to support this weird hack? As a result, we'll have to degrade IE9/10 so that StripMQ can still work, but ideally StripMQ would maybe just ignore media queries it doesn't understand?

I think I lifted this hack from http://wtfforms.com: https://github.com/mdo/wtf-forms/blob/master/wtf-forms.css#L186-L212

Thanks!

**Comment by jvennix-rmn** [comment]
+1

**Comment by jvennix-rmn** [comment]
Actually, `0\0` seems to work, the problem is when I pass this through sass I end up with `0 \0`, which fails:

```
TypeError: Cannot read property '1' of null
    at /Users/jvennix/Projects/grunt-stripmq/node_modules/css-mediaquery/index.js:105:36
    at Array.map (native)
    at /Users/jvennix/Projects/grunt-stripmq/node_modules/css-mediaquery/index.js:103:42
    at Array.map (native)
    at parseQuery (/Users/jvennix/Projects/grunt-stripmq/node_modules/css-mediaquery/index.js:88:34)
    at Object.matchQuery [as match] (/Users/jvennix/Projects/grunt-stripmq/node_modules/css-mediaquery/index.js:21:12)
    at /Users/jvennix/Projects/grunt-stripmq/tasks/lib/stripmq.js:11:28
    at Array.reduce (native)
    at stripMediaQueries (/Users/jvennix/Projects/grunt-stripmq/tasks/lib/stripmq.js:9:48)
    at StripMQ (/Users/jvennix/Projects/grunt-stripmq/tasks/lib/stripmq.js:43:12)
```

I will investigate to see if there's a way to prevent this behavior in sass. I don't see the point of supporting a malformed hack for IE here.

**Comment by oller** [comment]
+1 for this issue with sass compiling causing `stripmq` to error.

In the meantime, I found a workaround using a slightly different IE Media Query hack which `stripmq` doesn't have such a problem with:

``` html
@media screen\0 {
  ....
}
```

Props to : http://keithclark.co.uk/articles/moving-ie-specific-css-into-media-blocks/media-tests/ for the media query hacks.
